---
# Per environment values which override defaults in hmpps-approved-premises-manage-a-resident-api/values.yaml

generic-service:
  ingress:
    host: approved-premises-manage-a-resident-api.hmpps.service.justice.gov.uk

  env:
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
