---
# Per environment values which override defaults in hmpps-approved-premises-manage-a-resident-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: approved-premises-manage-a-resident-api-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
