---
# Per environment values which override defaults in hmpps-approved-premises-manage-a-resident-api/values.yaml

generic-service:
  serviceAccountName: hmpps-community-accommodation-api-service-account
  replicaCount: 2

  ingress:
    host: approved-premises-manage-a-resident-api-dev.hmpps.service.justice.gov.uk
    tlsSecretName: hmpps-approved-premises-manage-a-resident-api-dev-cert

  env:
    JAVA_OPTS: "-Xmx1000m"
    SPRING_PROFILES_ACTIVE: dev
    HMPPS_AUTH_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth

env_details:
  production_env: false
